# Generated by Django 2.2 on 2020-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('city_of_residence', models.CharField(blank=True, max_length=60)),
                ('about_me', models.TextField(blank=True)),
                ('highest_education', models.CharField(blank=True, max_length=60)),
                ('key_skills', models.CharField(blank=True, max_length=120)),
                ('total_experience', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '5-10'), ('11', '10+')], default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('employer_name', models.CharField(blank=True, max_length=60)),
                ('job_location', models.CharField(blank=True, max_length=120)),
                ('job_description', models.TextField(blank=True, max_length=120)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], default='Full-time', max_length=60)),
                ('key_skills', models.CharField(blank=True, max_length=60)),
                ('job_eligibility', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
