# Generated by Django 2.2 on 2020-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_category2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_category3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_proficiency2',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_proficiency3',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=30),
        ),
    ]
