# Generated by Django 2.2 on 2020-06-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0004_auto_20200630_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='assesment_category',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='assesment_score',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='employment_description',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='passing_grade',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='project_industry',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_category',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_category2',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_category3',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_proficiency',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_proficiency2',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill_proficiency3',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='university',
        ),
    ]
