# Generated by Django 2.2 on 2020-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0007_auto_20200630_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='last_employer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='passing_grade',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='passing_year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='stream',
            field=models.CharField(default='B.E/BTech', max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='university',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
