# Generated by Django 2.2 on 2020-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0008_auto_20200630_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='last_role',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='employer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='project_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_category2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_category3',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
