# Generated by Django 2.2 on 2020-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0009_auto_20200630_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='last_employer',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_role',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
