# Generated by Django 2.2 on 2020-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtalentpro', '0010_auto_20200630_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=60),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.PositiveIntegerField()),
                ('candidateprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtalentpro.CandidateProfile')),
            ],
        ),
    ]
